### PR TITLE
Building locks (Map Scene game transition)

### PR DESCRIPTION
**Pull request by casd82**
* Added new background for Home Scenario.
* Buildings of Map Scene will now be locked unless the previous scenario has been completed.
* Added `saveScenario` and `getScenario` methods to `DatabaseAccessor` so that scenarios could now be saved and fetched to and from the database.

lock

### CODE REVIEW

**Comment by casd82** [comment]
@jenpaff, solved conflicts.
Also, make sure to delete and reinstall the app before testing :)

**Comment by jenpaff** [comment]
@casd82 Oh no ! There's conflicts again!

**Comment by casd82** [comment]
@jenpaff , ouch, I'll fix that now.

**Comment by casd82** [comment]
Fixed :)

**Pull request merged**
