### PR TITLE
Added 3 facial features(eyes/hair/face),in the game app

### PR DESCRIPTION
**Pull request by YashBit**
Included two new designs in bags and two new hairstyles .

### CODE REVIEW

**Comment by sanyajain** [comment]
@YashBit The new designs of bags and hairstyles don't actually appear on the screen in the 2 dressing rooms. Make sure you've assigned the images properly. I am attaching the screenshot of dressing room-1.
screen shot 2017-01-07 at 1 00 35 pm

**Comment by YashBit** [comment]
@sanyajain Do I have to commit the json files too ?

**Comment by sanyajain** [comment]
@YashBit I am closing this PR

**Comment by YashBit** [comment]
@sanyajain  I have made the changes and created a new one

**Pull request closed without merging**
