### PR TITLE
Scenarios added. Karma points system implemented.

### PR DESCRIPTION
**Pull request by casd82**
* Added school, store, hospital, library, home scenarios to the game.
* Reimported database entries, so PowerUp-iOS shared the exact same database entires with PowerUp-Android.
* Added `getScore`, `saveScore`, `boughtAccessory`, `resetDatabase` methods to `DatabaseAccessor`
* Implemented the Karma points system (get Karma after each scenario, spend Karma on accessory store, reset Karma points and purchased accessories when a new avatar is created).
* Added an alert dialog if the player wants to create a new avatar (since the old avatar will be deleted).
* Solved the issue that database isn't persistent after relaunching the app.

### CODE REVIEW

**Comment by sunjunkie** [comment]
Let's get rid of the 'magic strings' and use enums. This will enable the compiler to check the type -
 you can't accidentally misspell a string. Below is an example:

// by Swift convention enums are lower case and enum names are plural
enum Accessory: String {
        case face
        case eyes
        case hair
        case clothes
        // ...
}

// But if upper case is necessary (for the database):

enum Accessory: String {
        case face = "Face"
        case eyes = "Eyes"
        case hair = "Hair"
        case clothes = "Clothes"
        // ...
}

// in Acessory.Swift

struct Accessory {
    // The type of the accessory. (i.e. Hair, Glasses, etc.)
    var type: Accessory

// enum usage in Avatar.swift
// the compiler knows the type is "Accessory" so you can leave it out; Xcode will also provide you a list of possible choices in its context sensitive help

    self.face = Accessory.face   
    self.eyes = .eyes
    self.hair = .hair
    self.clothes = .clothes
        
// and to get the actual string value
        
   public func boughtAccessory(accessory: Accessory) -> Bool {
        let queryString = "UPDATE \(accessory.type.rawValue) SET Purchased = 1 WHERE ID = \(accessory.id)"

**Comment by sunjunkie** [comment]
Also merge from systers to get the most recent merged changes into your branch.

**Comment by casd82** [comment]
Ah, did not think of that! Yeah, using enum will be way simpler. I'll modify the code now.

**Comment by casd82** [comment]
I added the `AccessoryType` enum, solved the merge conflict, and modified relevant code.

**Pull request merged**
