### PR TITLE
moving strings to strings.swift file

### PR DESCRIPTION
**Pull request by SIMRAN1**
Description
This PR adds all the strings of the project to Strings.swift file.

Fixes #221 

Type of Change:
Code
Code/Quality Assurance Only

New feature (non-breaking change which adds functionality pre-approved by mentors)
How Has This Been Tested?
App was tested successfully after adding the strings to string.swift file.
**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by sunjunkie** [comment]
Can you resolve the conflicts?

**Comment by SIMRAN1** [comment]
@sunjunkie  I have resolved conflicts ..Please review the changes..

**Comment by sunjunkie** [comment]
@SIMRAN1 This looks good. Can you edit the description to conform to the Pull Request Template? Then I will merge.

**Comment by SIMRAN1** [comment]
@sunjunkie thanks I have done the changes mentioned

**Pull request merged**
