### PR TITLE
Finish coding data model classes and database accessor singleton class.

### PR DESCRIPTION
**Pull request by casd82**
* Added data model classes: `Answer`, `Question`, `Avatar`, `Accessory`, so the database accessor singleton could communicate better with controller code.
* Implemented database accessor singleton to handle all database calls. Replaced the original database accessing code in controllers with single function calls to `DatabaseAccessor`. (Simply put, separated model code from controller code).
* Changed orientation from portrait to landscape. Adjusted views to adapt to landscape orientation.
* Deleted unneeded database "Choices.sqlite".

(Issue #70 Fixed)

### CODE REVIEW

**Comment by sunjunkie** [comment]
You should use the simpler Swift 3 pattern for singleton classes:

class ClassName {
  static let sharedInstance = ClassName()
  private init() {...} 
}

then access the singleton :  ClassName.sharedInstance.somefunc()

And then you don't need to check for whether the instance is nil.

**Comment by casd82** [comment]
@sunjunkie , it is modified!

**Comment by sunjunkie** [comment]
There are still several instances of **DatabaseAccessor.sharedInstance()** so the project does not compile.  (need to remove parentheses)

**Comment by casd82** [comment]
Oops, not sure why I did not compile the class for testing in the first place.
The compiler errors are all fixed now.

**Pull request merged**
