### PR TITLE
Moving constants to seprate file

### LINKED ISSUE #222: Moving Constants to a seprate file
## Description
As a developer all constants should be kept in seprate file.
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours 
I want to work on this issue

### PR DESCRIPTION
**Pull request by SIMRAN1**
### Description
Moved all constants to seprate file.

Fixes #222 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by SIMRAN1** [comment]
@sunjunkie please review the pr

**Comment by sunjunkie** [comment]
Simply extracting the constants into a separate file is not a good enough solution. We lose all context of what the constants mean. And if a constant will only ever be used in one class only, it does not make sense at all. 
It is much better to group the constants into separate 'types'  where the type name provides some meaning to the constant. These type namespaces can be implemented with enums. See [Documentation](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Enumerations.html#//apple_ref/doc/uid/TP40014097-CH12-ID145).
In some use cases, caseless enums with static let properties is even better (avoids the "rawValue" requirement for enums and the chance of accidental instantiation.) See [example](https://github.com/raywenderlich/swift-style-guide#constants).

**Comment by SIMRAN1** [comment]
okk @sunjunkie mam I have seen this approach..Now should I group constants using enums and solve this issue.??

**Comment by sunjunkie** [comment]
You can work on this. It would be good to discuss your approach before you code in Slack/#powerup.

**Comment by SIMRAN1** [comment]
okk @sunjunkie  mam I will discuss in slack group.

**Pull request closed without merging**
