### PR TITLE
Adding Game Completion Screen.

### LINKED ISSUE #242: Addition Of Game Completion Screen.
## Description
As a user, I want to see my karma points at the end of the game so that I know how many karma points I have in total.This feature is implemented in android.

## Mocks

image

## Acceptance Criteria
When Completion Screen is added.
### Update [Required]
- [ ] [LIST ITEMS]
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
2 hours

### PR DESCRIPTION
**Pull request by SIMRAN1**
### Description
Added Game completion screen to make app consistent with android and to notify user when the game is completed.

Fixes #242 
image

### Type of Change:
**Delete irrelevant options.**

- Code
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Game completion screen is added after Library scenario completion.I have tested it in simulator.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by SIMRAN1** [comment]
@sunjunkie mam and @zenara mam please review the pr!!

**Comment by SIMRAN1** [comment]
@zenara mam Actually I have discussed with @sunjunkie mam slack thread https://systers-opensource.slack.com/messages/C0C9VK8UE/convo/C0C9VK8UE-1523036369.000322/ .Once changes are approved I will squash it.

**Comment by SIMRAN1** [comment]
@sunjunkie mam I have done the mentioned changes.

**Comment by SIMRAN1** [comment]
Okk @sunjunkie mam I will resolve the conflicts!!

**Comment by SIMRAN1** [comment]
@sunjunkie mam I have resolved the conflicts.

**Comment by SIMRAN1** [comment]
@sunjunkie  mam I have rebased the branch and resolved conflicts! Please review it..

**Comment by sunjunkie** [comment]
In your changes in ResultsViewController, you set "nextScenarioID = 5". First, you are using a "magic number" with no explanation of what it means. Second, the variable name you use (nextScenarioID) is very confusing. Not only is it the same name as the scenario property, but the name does not reflect what this item actually represents - which is, specifically, the id of the end view.

**Comment by SIMRAN1** [comment]
okk @sunjunkie  mam I will change it.

**Comment by SIMRAN1** [comment]
@sunjunkie mam I have used Scenario Name instead of ScenarioId to make code more understandable!!

**Comment by SIMRAN1** [comment]
okk @sunjunkie mam I will do the mentioned change!

**Comment by SIMRAN1** [comment]
@sunjunkie mam I have done the mentioned change!

**Pull request merged**
