### PR TITLE
Added ui tests for StorySequencePlayer

### LINKED ISSUE #268: Setup UI tests for intro story sequences
## Description
As a developer,
I need to design UI tests for StorySequencePlayer intros, so that I can ensure all scenarios will work as the app evolves.

### Update [Required]
- [ ] Adds UI test for intro sequences on existing scenarios.
- [ ] Tests should check for an intro sequence for the given scenario, run through it, and assert the expected app state.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

### PR DESCRIPTION
**Pull request by justKD**
### Description
Fixes #268

Added UI tests for StorySequencePlayer

- test launching and stepping through a sequence
- test the skip function

This test assumes there is a home intro. It should be changed to unlock and test a different sequence if one does not exist at some point.

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

Both tests pass.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by justKD** [comment]
The Travis test was failing because my test assumed there was a saved game. This last commit should account for that.

**Comment by justKD** [comment]
I can't tell what's going on now. Travis says it's failing when it tries to scroll something into view:
screen shot 2018-06-01 at 3 28 27 pm

But the tests do no such thing. They pass in Xcode.
screen shot 2018-06-01 at 3 29 09 pm

**Comment by sunjunkie** [comment]
The UI tests fail when I run them on Iphone 6 (9.3) simulator which is close to what the Travis command is: "xcodebuild -project Powerup.xcodeproj -scheme Powerup -sdk iphonesimulator11.2 -destination **'platform=iOS Simulator,OS=9.1,name=iPhone 6'**  -configuration Debug build test"

The UI tests succeed when I run them on iphone 6 (11.4). So I would look at the iOS version differences.

**Comment by sunjunkie** [comment]
The tests also succeed on iphone 6 (10.3.1) simulator. Since 95% of iOS devices are running iOS 10/11 and iOS 12 is coming out this fall, I am ok with bumping up the target deployment to iOS 10 and dropping support for iOS 9. iOS tends to have a high rate of upgrade adoption and iOS 10 is compatible with iPhones as far back as iPhone 5. So don't get caught down a rabbit hole. :-)

**Comment by justKD** [comment]
That sounds good too. Honestly though, I’m also kind of curious what could be so different that it fails on iOS 9.

**Comment by justKD** [comment]
So what's different? Nothing really. Except apparently Xcode automatically assigns the identifier of "2" to the home scenario button in iOS 10+, but assigns "4" in iOS 9.

screen shot 2018-06-07 at 2 14 11 am

The test could find the button and confirm it existed, and log its properties, and I could click on it manually. But when it went to automate clicking, it couldn't find it because it says element 2 doesn't exist as a clickable entity. Element 4 does.

Which is still weird to me... It would make more sense is element 2 existed but was just the wrong button. But no, element 2 doesn't exist in iOS 9.

**Pull request merged**
