### PR TITLE
updating README.md file

### LINKED ISSUE #245: update ReadMe File
## Description
As a developer,
I need to update README.md,
so that Information available is consistent with the repository and beginner get proper direction in contributing to the project.

## Acceptance Criteria
When proper description of git commands is done in readme file and contributing guidelines are updated properly and linked to readme file.
### Update [Required]
- [x] [README]

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
2 hours

### PR DESCRIPTION
**Pull request by SIMRAN1**
### Description
Updated README.md file with proper git commands and updating contributing guidelines of project.

Fixes #245

### Type of Change:
**Delete irrelevant options.**

- Documentation

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by SIMRAN1** [comment]
@sunjunkie mam and @zenara mam please review the changes and suggest some more addition if required.

**Comment by SIMRAN1** [comment]
@sunjunkie mam for wiki edit "How to contribute guidelines" I have made a repo in github https://github.com/SIMRAN1/powerup-iOS-wiki   .Please review it and suggest changes.I have made changes according to android wiki documentation.

**Comment by sunjunkie** [comment]
1 - Change the "!" after the first sentence to a "."
2 - There are many missing carriage returns. Go through the document and insert new lines where needed.
3 - Step 5 about building in Xcode is unnecessary. Remove that line.
4 - Change the line "5.Fetch the latest version of code from branch "develop"." to "5. Fetch the latest version of code from the appropriate branch (usually "develop")."

**Comment by SIMRAN1** [comment]
okk @sunjunkie mam I will do the mentioned changes!

**Comment by SIMRAN1** [comment]
Okk @sunjunkie mam I will do the changes mentioned!!

**Comment by SIMRAN1** [comment]
@sunjunkie mam I have done the mentioned changes please review it.

**Pull request merged**
