### PR TITLE
Class handling intro sequences does not interfere with existing scenario setup

### LINKED ISSUE #265: Intro class does not interfere with scenario launch
## Description
As a developer,
I need the intro story sequence to not change the way scenarios are already launched,
so that I can ensure it can be safely managed without breaking other game content.

### Update [Required]
- [ ] Intro sequence can be invoked by simply overlaying a view on the existing view controller
- [ ] Disables interactions on the existing vc
- [ ] Re-enables interactions once the intro view is disposed

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

### PR DESCRIPTION
**Pull request by justKD**
### Description
Fixes #265 

Began implementing StorySequencePlayer class. Tested to ensure it will not interfere with existing setup and launch for scenarios.
- is a subclass of UIView
- ScenarioViewController checks to see if an intro sequence should be played for the given scenario
- StorySequencePlayer instance is created and added as a full screen subview
- ScenarioViewController is the delegate and removes the instance from its subviews when the sequence is ended
- the overlay has a dark blurred background and responds to a tap gesture

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
- Doesn't require a strong reference, so the only code changes are implementing a new function to create a local instance of the class, and the delegate method where it is dismissed
- I've added the relevant code with mock data where the Home scenario should create and display the view, and other scenarios should not.
- Tested to ensure the view is added when it should be, and that it dismisses, revealing the regular scenario view.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by sunjunkie** [comment]
I'm not getting an inline popup after clicking on 1A.  
Also, did you mean to check "I have added tests...."?

**Comment by justKD** [comment]
!!! I just checked out the branch, and I'm not having any trouble displaying the popups. Does the rest of the navigation work correctly?

**Comment by justKD** [comment]
And no, I haven't added any specific tests. I've tested it, but I still need to set up the UI test target and design some tests.

**Comment by sunjunkie** [comment]
Everything looks the same except that I don't get the 1st popup ("test model 1").

**Comment by justKD** [comment]
I think I got it. I had made some manual changes to the db in order to make debug messages more readable for myself. I got the popupID wrong for the first question... You might need to uninstall the app in order to get the latest version of the database now. I never got the bug because Xcode apparently doesn't overwrite the sqlite db.

**Pull request merged**
