### PR TITLE
Changed functionality of Level 1 button

### PR DESCRIPTION
**Pull request by sarayd**
Level 1 button now allows user to play twice before sending error
message

### CODE REVIEW

**Comment by sarayd** [comment]
@sanyajain I wasn't sure if you were able to receive my message through the GCI portal since it's closed now, but do you mind looking at my last commit? I added some features to level 2 and just wondering if I'm taking the right approach :)

**Comment by sanyajain** [comment]
@sarayd I did get your message. Sorry, couldn't check your commits earlier, wrapped in assignment submissions and stuff.
About the task on animation, I found the animations really nice and creative. I hope you had a good time doing that.. Animations are cool and introducing them is not-so-easy also, so good job there :) I guess you animated 3 screens, right? For further animations and changes, we might have to talk to project managers because we want to make sure that our project is consistent with the proposed design and mechanics and also in sync with the Android version. 
About the other commit, I couldn't really understand what you did there. I'll reiterate the task here, if you want. Basically our intention is to introduce the feature of "Health and Powers". There are mainly 4 powers (you can see 4 bars at the bottom in the sample picture attached at the end of each level 2 scenario). Theses are 4 powers namely, "Healing" "Strength" "Invisibility" "Telepathy". So after playing each scenario, user gains/loses these powers depending on the choices made by him/her. These are basically the character traits of the Avatar that stay with him/her even after the completion of a scenario. Although it's probably a feature for future iterations of the game development but I just wanted you to have a flavour of the problem and lay the basic framework for it. You can discuss here if you have any questions.

**Comment by sarayd** [comment]
no problem! oh yeah, the Android version would have to include the same animations, but I had fun doing it anyways :) turns out there are quite a lot of ways to do animation! 
Ah ok, I wasn't fully aware of all the requirements, so I just included that sample bar at the bottom. The code I had stored the health values for the user and adjusted the bar accordingly, so I'm probably just going to use the same code and implement it across the view controllers and create four bars instead :smile:

**Comment by sarayd** [comment]
also, @sanyajain I'm not sure if you heard yet, but Parse is closing down its service :( it comes as such an ironic surprise since I wrote about it as an alternative database

**Comment by sanyajain** [comment]
@sarayd Oh no, I just heard from you. That's indeed sad. But at least we concluded that Realm would be the future and the next best alternative :smile:

**Comment by sanyajain** [comment]
@sarayd You've made significant contribution to PowerUp and I spoke to the admins about merging your commits to the main project. However, not all commits have to be merged... 
I shall make a list of commits that I think can be merged right now (and forward the same to the admins and get their approval).. But I reckon the merging the entire branch would be easier. I'll have to check if that would be fine or not. Else I think we'll have to selectively merge/cherry pick..

**Comment by sarayd** [comment]
oops! nevermind, i accidentally confused parse with realm haha. it's still sad to hear about it, but at least realm is still there.
Wow! that sounds great :D yeah there are some commits that may be better than the others, and the entire branch has been changed to the latest commit so I'm not sure if that would be the best. what else do you think there needs to be done that I can help with for powerup? :)

**Comment by sanyajain** [comment]
@sarayd The entire branch has been changed to last commit but will I be able to merge all the significant changes that you made? I mean you did all the tasks independently, right? Every time you downloaded a fresh copy of systers/powerUp-iOS repo and made the changes?

**Comment by sanyajain** [comment]
The last commit is animation and it has changes only related to that specific task.
Do you happen to have your local copy of the project where you have all the changes?

**Comment by sarayd** [comment]
No i did not keep a master :( well, I can revert each commit to get access to the previous capabilities added, will that work?

**Comment by sarayd** [comment]
@sanyajain

**Comment by sanyajain** [comment]
Yeah, You can revert commits to get access to the previous capabilities but you'll have to build the next subsequent commits on top of that so that the previous functionalities are retained so that the branch is updated to the latest commit and the code can be merged @sarayd

**Comment by sarayd** [comment]
how would I do that? is there a way to merge commits? @sanyajain

**Comment by bphenriques** [comment]
@sarayd 
Can you look git pull --rebase ? This should apply your commits after the latest changes in master. You will have to solve every conflict as git tries to apply your commits on top. I would suggest, both for better readability and to ease the merging process, to squash your commits into a single one ("Try again", "edit", "customize"). B

etter commit messages is something that only recently I have been valuing, so at least squash your commit into concise ones before PRs is better for you and for the one who is reviewing.

See this: https://stackoverflow.com/questions/14534397/squash-all-my-commits-into-one-for-github-pull-request

**Comment by sarayd** [comment]
@bphenriques the thing is, how would I squash them together if some of the functionality is added then deleted in subsequent commits? Does github know to automatically add everything I want together? Sorry, I've never done this before and its pretty confusing to me

**Comment by bphenriques** [comment]
Every removal and add is tracked by a commit. There are ways to select specific commits I think but never used. The simplest way is to squash the previous N commits into a single one (all your commits into a single commit with the message "Add: Level 1 button now allows (...)". For how to squash previous N commits refer to the link I posted earlier in "See this". 

After you squash your commits: http://gitready.com/advanced/2009/02/11/pull-with-rebase.html. This will apply your squash single commit after the previous master changes. Afterwards you can resubmit your pull request

**Comment by sanyajain** [comment]
@sarayd Try and squash the last 2 commits into one(animation and added powers bar) the way suggested in the link posted @bphenriques and check what errors you get (if any). Then you could try and squash more commits. Also, there are certain commits that don't need to be merged so right now don't squash all of them together.

**Comment by sarayd** [comment]
@sanyajain I squashed it and the squash commit appeared in my github desktop, but when I sync, I don't see it as a commit in my repo. is that supposed to happen?

**Comment by sanyajain** [comment]
@sarayd I haven't done it before but that shouldn't happen, it should definitely show here. Maybe @bphenriques may know more

**Comment by bphenriques** [comment]
@sarayd No error? You have to probably do push -f origin master (force as
you want to overwrite the online state of your repo with the one you have
locally)

2016-02-09 16:49 GMT+00:00 sanyajain <notifications@github.com>:

> @sarayd <https://github.com/sarayd> I haven't done it before but that
> shouldn't happen, it should definitely show here. Maybe @bphenriques
> <https://github.com/bphenriques> may know more
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/systers/PowerUp-iOS/pull/18#issuecomment-181952706>.
>



-- 
Os melhores cumprimentos,
Bruno Henriques

**Comment by sanyajain** [comment]
@sarayd Any progress? Did you try force push command?  Or are you getting errors ? If there are some errors you could post them here, I'll try to help.

**Comment by sarayd** [comment]
@sanyajain i message you through slack with what I tried to do and what github's showing me. would you prefer it if I just messaged you through here?

**Comment by sanyajain** [comment]
@sarayd Sorry, I just checked slack, so you clicked on Sync in GitHub for Mac and it doesn't show here, eh? Well, try from command line with -f for force push instead of doing it from here. Probably that will solve the problem

**Comment by sunjunkie** [comment]
Closing this since it is outdated.

**Pull request closed without merging**
