### PR TITLE
New Shop UI

### PR DESCRIPTION
**Pull request by casd82**
Refactored and applied new UIs for Shop Scene.

simulator screen shot 2017 8 11 10 30 55

### CODE REVIEW

**Comment by casd82** [comment]
Also applied the new UIs to Result Scene.

**Comment by jenpaff** [comment]
@casd82 Can you resolve the conflicts here too please? Also please give me a shout if the PR is ready for testing

**Comment by casd82** [comment]
@jenpaff, the conflicts are fixed for this branch as well.

**Comment by sunjunkie** [comment]
@casd82 Did you take out the option to unselect an item to buy? Plus I'm a little confused by the green check marks.

**Comment by casd82** [comment]
@sunjunkie Yes I took out the option to unselect an item because I updated the Store Scene according to Kim's pull request:
https://github.com/systers/powerup-android/pull/453/files

Also, it seems like the Android version don't have the revert functionality either. We could always add the revert functionality back since there are existing code in the previous commits, maybe I'll discuss this with them.

The green checkmark means "item bought". The greyed out box means "not enough money". However, since it confuses you, I guess it might confuse other people as well. I will discuss this issue   with the team and see how it could be changed.

**Comment by sunjunkie** [comment]
I didn't actually purchase all the items that have a green check. That's my confusion.

**Comment by casd82** [comment]
@sunjunkie There are some items that are purchased by default. Those are the ones which the players could choose when they first start the game (aka. in the Customize Avatar Scene).

**Pull request merged**
