### PR TITLE
naming the unnamed segue and replacing debugprint with assertion Failure

### LINKED ISSUE #237: Name the unnamed segue in the project.
## Description
As a developer,
I need to name the segues defined in  the project,
so that segue didnot throw nil value.Unamed segue throw nil value..

## Mocks
[INSERT RELEVANT PNG FILE]

## Acceptance Criteria
All unamed segues are named.
### Update [Required]
- [ ] [LIST ITEMS]
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours 
I want to work on this issue.

### PR DESCRIPTION
**Pull request by SIMRAN1**
### Description
naming the unamed segue in project.All the unamed segues are named because unamed segues was throwing nil value.

Fixes #237

### Type of Change:
**Delete irrelevant options.**

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
All the segues named are tested.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by SIMRAN1** [comment]
@sunjunkie mam please review the pr.

**Comment by sunjunkie** [comment]
Please complete the PR template sections above.
Regarding your changes:
1. The debugPrint statements are unnecessary for the unwind segues in the switch statement.
2. The output statement in the assertionFailure is missing information. (e.g., what 'string'?)

**Comment by SIMRAN1** [comment]
okk @sunjunkie  mam.

**Comment by SIMRAN1** [comment]
@sunjunkie I have done the mentioned changes.

**Comment by sunjunkie** [comment]
Please change "Did not recognize storyboard identifier \(segue.identifier)" to be more specific:  "Did not recognize **segue** identifier \(segue.identifier)"

**Comment by SIMRAN1** [comment]
@sunjunkie  mam I have done the mentioned changes!

**Pull request merged**
