### PR TITLE
Dialogue scrolling

### PR DESCRIPTION
**Pull request by casd82**
* Updated dialogue images, so they have lighter stripes.
* Updated the new hospital scenario background image.
* Use `UITableView` instead of buttons for the choices in scenarios, so that the player could scroll down for more choices.
* Karma point will be added after the "Gain Karma" pop up is shown.

(This branch should be merged after #116 )

### CODE REVIEW

**Comment by casd82** [comment]
Yeah I really like UITableView, so convenient :D!

**Comment by casd82** [comment]
@jenpaff, could you send a screenshot of this issue? I'm not quite sure about what you mean.

**Comment by jenpaff** [comment]
screenshot_powerup
(see bottom response option) 

Is that also happening your simulator ?

**Comment by casd82** [comment]
@jenpaff, oh, actually I intentionally make it look like that so that I will be the same as the design of Android. You can scroll the dialogue down by dragging.

**Comment by jenpaff** [comment]
Ok, my bad !

**Pull request merged**
