### PR TITLE
adding segue handler type.swift and making segue safer

### LINKED ISSUE #219: Adding Segue identifiers to a Seprate class Constants.swift
## Description
Adding segue identifier into Seprate class..All the segue identifiers will be moved to constants.swift.

## Estimation
2 hours 
@sunjunkie @MeepyMay What's say about it?.
I want to work on this issue.

### PR DESCRIPTION
**Pull request by SIMRAN1**
### Description
This PR makes segue safer by using enums.

Fixes #219 

Type of Change:
Code
Code/Quality Assurance Only

New feature (non-breaking change which adds functionality pre-approved by mentors)
How Has This Been Tested?
App was tested successfully after  modifying the segues code to make it safe.

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by SIMRAN1** [comment]
@sunjunkie please review this pull request

**Comment by sunjunkie** [comment]
@SIMRAN1 Looks like I edited the old PR while you were submitting a new one. :-) Here are my comments.

1. Remove “Type” from name according to Swift guidelines: Swift.org - API Design Guidelines
2. ~~Fix indentation in new SegueHandler file~~
3. In SegueHandler extension function "segueIdentifierForSegue", the 1st if statement is unnecessary. The guard statement will handle the nil input.
4. In .none case option, replace the print with assertionFailure statement to catch this at debug time.

**Comment by SIMRAN1** [comment]
@sunjunkie I have used if statement because in main.storyBoard there is no segue indetifier that means segue identifier is nil.Hence app was throwing an error shown in guard statements..

**Comment by SIMRAN1** [comment]
@sunjunkie please review the pr I have done the mentioned changes

**Comment by SIMRAN1** [comment]
@sunjunkie mam I think use of AssertionFailure will lead to failure in app like in MapViewController pressing home icon returns nil value hence I have used a simple debugPrint statement.

**Comment by SIMRAN1** [comment]
@sunjunkie I think we should not use AssertionFailure in MapViewController as in many cases segue identifier returns nil hence failure occurs..All the other changes Mentioned are done please review it.

**Comment by sunjunkie** [comment]
If you name the segue in the storyboard, the segue identifier will not be nil. However, we can make a new issue for unnamed seques in the code.

**Comment by SIMRAN1** [comment]
okk @sunjunkie I will create the issue for it.

**Pull request merged**
