### PR TITLE
Allow two clicks on "Level 1"

### PR DESCRIPTION
**Pull request by ndrewh**
Also converted to Swift 2.0 so that I could actually build it. GCI Task: https://codein.withgoogle.com/dashboard/task-instances/5857160114208768/

### CODE REVIEW

**Comment by sanyajain** [comment]
@ndrewh Hi! Did you try building the project on xcode? I just tried running it and the build fails with many compilation errors.
screen shot 2015-12-08 at 1 37 15 pm

**Comment by ndrewh** [comment]
Hmm, it built and ran fine on my version of Xcode. Make sure you are using the latest Mac App Store version of Xcode (I think it's 7.1 or 7.2 or something, don't have it in front of me). Older Xcodes come with old swift compilers that don't support all the new stuff.

**Comment by ndrewh** [comment]
@sanyajain

**Comment by sanyajain** [comment]
@ndrewh I shall try running it again and will let you know ASAP, I don't have my mac right now. Could you tell me what exactly have you done in your first commit?

**Comment by ndrewh** [comment]
Xcode (latest version) prompted me to upgrade to the latest syntax, and I let it do its job. It also wanted me to upgrade to the latest "project settings", which I also let it do.

**Comment by sanyajain** [comment]
That might have caused all those errors. Since the existing project and code has been built according to the older syntax and settings.

**Comment by ndrewh** [comment]
Correct, the errors you are seeing would be from an incompatibility between the latest Swift syntax (which my Xcode migrated the code to, as seen in the first commit), and whatever version of Xcode you are using.

Just checked my Xcode version. It looks like I'm on 7.1.1. Xcode 7.2 was released today.

What version are you on?

**Comment by ndrewh** [comment]
See #15

**Comment by sanyajain** [comment]
@ndrewh Good job! Just checked it, it's running fine! :)

**Pull request closed without merging**
