### PR TITLE
Sink to swim game

### PR DESCRIPTION
**Pull request by casd82**
Completed the Sink to Swim game prototype with changes discussed last meeting: 
* Timer now counts down.
* Boat now has a wobbling animation
* Score now has a simpler mechanic
* The game now has an ending scene.

To test the game, choose Library Scenario. All the endings lead to Sink to Swim game.

### CODE REVIEW

**Comment by casd82** [comment]
Solved conflicts.

**Comment by jenpaff** [comment]
I found that when completing the game the total score isn't showing at the end. Can you try if thats working for you please?

**Comment by casd82** [comment]
@jenpaff Seems like I accidentally mistyped a variable. It is fixed now.

**Comment by jenpaff** [comment]
Ok Great- the rest looked good ! I will test the changes again

**Pull request merged**
