### PR TITLE
UI updates (7/25)

### PR DESCRIPTION
**Pull request by casd82**
UI updates:
* Added App Icon.
* Added splash screen.
* Changed start scene.
* Added a replay button on the results view, so that players can replay that scenario again.

(Since the UI is constantly updating, I'll add the date at the end of the title for each PR.)

### CODE REVIEW

**Comment by casd82** [comment]
I agree with all of your points except that I think we should remain the texts of the buttons as "New Game" and "Load Game". Since, first of all, most games use the exact same term (new game/load game) in there menu scene, so people will more likely to understand the meanings of the buttons. Secondly, I think the "New Game" button means "Restarting the entire game from the very beginning" instead of simply "Changing the avatar", and the "Load Game" button means "Loading the game state of my previous game" instead of just starting the game. After all, if a player wants to change (the appearance of) their avatar after the game is started, they should go to the Shop Scene.

I will push the changes for point 1 and 3 later. For point 2, we should discuss further.

**Comment by casd82** [comment]
I pushed the changes of point 1 and 2.

**Comment by sunjunkie** [comment]
OK, I understand your points and I agree with what you suggest. So, to summarize, the New Game button is for starting a new game from scratch with a new avatar, 0 points, etc. and the Load Game button is for when you are at the home screen and want to continue your previous game.

**Comment by casd82** [comment]
I pushed another commit, making the game transits directly to the Map Scene when the continue button is pressed in the CustomizeAvatarView, so users won't have to go back to the Start Scene after configuring their avatar.

**Pull request merged**
